name: Update GitHub Stats

on:
  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Download GitHub Stats Image
        run: |
          mkdir -p assets
          curl -s "https://github-readme-stats.vercel.app/api?username=adarsh-rajesh&show_icons=true&rank_icon=github&count_private=true&include_all_commits=true&hide_border=false&border_color=A55CFF&title_color=A55CFF&icon_color=A55CFF&text_color=F4F4F6&bg_color=090014&PAT_1=${{ secrets.GH_STATS_TOKEN }}" -o assets/github-stats.svg

      - name: Download Top Languages Image
        run: |
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=adarsh-rajesh&layout=compact&hide_border=false&border_color=A55CFF&title_color=A55CFF&text_color=F4F4F6&bg_color=090014&count_private=true&PAT_1=${{ secrets.GH_STATS_TOKEN }}" -o assets/top-languages.svg

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update GitHub stats images [skip ci]" && git push)
